
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRIYA
 */
public class pianoFrame extends javax.swing.JFrame {

    /**
     * Creates new form pianoFrame
     */
    public pianoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Piano");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("D1");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 60, 170));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("c");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 170));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("D");
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 60, 170));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("E");
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, 170));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("F");
        jButton5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 60, 170));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("G");
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, 170));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("A");
        jButton7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 60, 170));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("B");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 60, 170));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("F1");
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 60, 170));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("c1");
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 60, 170));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("E1");
        jButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 60, 170));

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("C#1");
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 70, 120));

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("C#");
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 120));

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("D#");
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 70, 120));

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("F#");
        jButton15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 70, 120));

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setText("G#");
        jButton16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 70, 120));

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setText("8b");
        jButton17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 70, 120));

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton18.setText("D#1");
        jButton18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 70, 120));

        pack();
    }// </editor-fold>                        

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-c_C#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }



    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-eb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }
    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-f_F#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }    }                                        

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }       }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }               }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_D#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }       }                                         

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_D#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }       }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }       }                                        

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }             }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_D#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }             }                                         

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_F#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }             }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }            }                                         

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_D#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }            }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_F#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }             }                                         

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_D#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }             }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_A#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }             }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try{
        String path="C:\\Users\\PRIYA\\Music\\piano\\piano-bb_D#_major.wav";   
        AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
        Clip player=AudioSystem.getClip();
        player.open(audio);
        player.start();
        }
        catch(Exception e){
            
        }       }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pianoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
